version: '3'
services:
  web:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - postgres
    volumes: 
      - .:/app
    ports:
      - 8000:8000
    env_file:
      - ./.env
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    ports:
      - '5432:5432'
    restart: always
    env_file:
      - ./.env
    volumes:
      - postgres-db:/var/lib/postgresql/data
  react:
    build: 
      context: ./easylab
      dockerfile: dockerfile.react
    command: npm run start
    depends_on:
      - web
    volumes:
      - .:/easylab 
    ports:
      - 3000:3000
volumes:
  postgres-db: