"""Add user_id to calculations table

Revision ID: 3238558141e7
Revises: 254ff0355cfb
Create Date: 2023-03-12 11:33:42.526523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3238558141e7'
down_revision = '254ff0355cfb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calculations', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'calculations', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'calculations', type_='foreignkey')
    op.drop_column('calculations', 'user_id')
    # ### end Alembic commands ###
