"""Added calculations table

Revision ID: a6fd4fc65288
Revises: fb711d75f2f9
Create Date: 2023-03-12 10:52:41.797290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6fd4fc65288'
down_revision = 'fb711d75f2f9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calculations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('from_', sa.String(), nullable=False),
    sa.Column('to', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('calculations')
    # ### end Alembic commands ###
