"""add creation date to convertions

Revision ID: f01c23215094
Revises: df09e1b0ce58
Create Date: 2023-03-12 11:46:27.551466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f01c23215094'
down_revision = 'df09e1b0ce58'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('convertions', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('convertions', 'created_at')
    # ### end Alembic commands ###
