"""Add dilutions table

Revision ID: d02f7c29dc98
Revises: f01c23215094
Create Date: 2023-03-19 17:32:59.389737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd02f7c29dc98'
down_revision = 'f01c23215094'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dilutions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('c1', sa.Float(), nullable=True),
    sa.Column('v1', sa.Float(), nullable=True),
    sa.Column('c2', sa.Float(), nullable=True),
    sa.Column('v2', sa.Float(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dilutions')
    # ### end Alembic commands ###
