"""Add calculations table

Revision ID: 254ff0355cfb
Revises: fb711d75f2f9
Create Date: 2023-03-12 11:18:37.726708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '254ff0355cfb'
down_revision = 'fb711d75f2f9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calculations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('from_', sa.String(), nullable=False),
    sa.Column('to', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('value_from', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('calculations')
    # ### end Alembic commands ###
